### ISSUE TITLE
Shaded rows hard to read in Dolphin list view (light mode)

### ISSUE THREAD

**Issue by Eilyra** [qewer33/leaf-kde#1]
When using the light color scheme, the row shading of evenly numbered rows is so dark as to almost completely obscure the text which is also dark.

![image](https://user-images.githubusercontent.com/5540445/159270006-63fa6baa-b8ac-4c38-bb4e-f2f581094171.png)

**Comment by qewer33** [comment]
Thanks for the report. Should be fixed with a95219bb6f666779eead80460f558b817352dcf6. Please update and confirm.

**Comment by Eilyra** [comment]
Yup, works! :+1:
