### ISSUE TITLE
The toggles in Networks dropdown are hard to see

### ISSUE THREAD

**Issue by oowais** [qewer33/leaf-kde#10]
This behavior is seen in both light and dark versions

Here is a screenshot of both
![image](https://github.com/user-attachments/assets/cb980cfe-61db-4341-9383-50e78d9fe559)
![image](https://github.com/user-attachments/assets/155bde38-af51-4eb5-99c9-f577c41d48ff)

FYI: wifi is enable and airplane mode is disabled

**Comment by qewer33** [comment]
Thanks for the report! Fixed now.

![Screenshot_20240806_171055](https://github.com/user-attachments/assets/b1187a4a-8682-4b18-9715-a99c7bef54ae)
![Screenshot_20240806_171107](https://github.com/user-attachments/assets/eaf99378-215b-4558-955a-dbf7f1d7f496)

**Comment by qewer33** [comment]
It looks slightly different on Network though, not sure why.

![image](https://github.com/user-attachments/assets/e67710db-db8b-48a7-972d-6eccf05d20f6)

**Comment by oowais** [comment]
At least the toggles are visible! Thanks for quick update! :)
