### ISSUE TITLE
Active window almost indistinguishable from inactive windows

### ISSUE THREAD

**Issue by monzool** [qewer33/leaf-kde#3]
First of all, thank you for a very nice kde theme! :trophy: 

I wonder if it could be a consideration to make the active window stand more out from the inactive ones? 

Currently only slightly grayed vs black icons in the window title bar, differs the inactive windows from the active. When having many window open upon multiple monitors, its easy to loose track of the active window, and one have to scan, potentially a lot, before finding the active window. A suggestion could be to color the window title bar of the active window in "leaf green". That would really make the active window easy to locate

**Comment by qewer33** [comment]
Thanks for the suggestion, I also had this in mind for a while now. Added colored titlebars versions of the aurorae themes for both light & dark.
https://store.kde.org/p/1748461
https://store.kde.org/p/1748463
