### ISSUE TITLE
components.rb bugs

### ISSUE THREAD

**Issue by yuhldr** [qewer33/leaf-kde#4]
[components.rb](https://github.com/qewer33/leaf-kde/blob/main/components.rb) maybe error

![image](https://user-images.githubusercontent.com/25719023/161295627-ca42b394-3174-462b-b4cd-83314eaff738.png)

```ruby
Component.new("konsole-colors", "./konsole", "#{Dir.home}/.local/konsole"),
```

should be

```ruby
Component.new("konsole-colors", "./konsole", "#{Dir.home}/.local/share/konsole"),
```

**Comment by qewer33** [comment]
Ah yeah that's right, thanks for reporting. 852984cc5c96a3309674c4c1125b2b6ccd8ab627
