### ISSUE TITLE
Completion in Konsole theme is invisible 

### ISSUE THREAD

**Issue by marknefedov** [qewer33/leaf-kde#5]
It is really hard to read because of "Color 1 Intense color" is too dark.
![Screenshot_20220401_215823](https://user-images.githubusercontent.com/20001291/161325324-92355099-fc4d-417f-8b02-6094e700cd77.png)
![Screenshot_20220401_215850](https://user-images.githubusercontent.com/20001291/161325329-35213c5f-433c-4155-9cce-9fffa37a2551.png)

**Comment by qewer33** [comment]
Ah I see, "intense" colors on dark themes need to be lighter. Thanks for reporting. 57511db6fad034c6ee16636487ae7a8e132e58fc
