### ISSUE TITLE
Some elements with enabled window color toning are black

### ISSUE THREAD

**Issue by stepanzubkov** [qewer33/leaf-kde#8]
Hello!
## Problem
I use window color toning (added in plasma 5.25). In Breeze ligth theme it is works properly. But with Leaf light theme it's not working.
Some elements are black.

__dropdown windows__

![Screenshot_20221001_163243](https://user-images.githubusercontent.com/83695097/193412271-7a6bc3ae-1eea-4a41-8939-2f2dda4fdb26.png)

__applications menu__

![Screenshot_20221001_163259](https://user-images.githubusercontent.com/83695097/193412273-dd45c519-398d-41ce-ae4e-c09b966af6c3.png)

__system settings__

![Screenshot_20221001_163107](https://user-images.githubusercontent.com/83695097/193412301-ccec10ad-b777-4157-886a-cfabf641439a.png)

__dolphin__

![Screenshot_20221001_163140](https://user-images.githubusercontent.com/83695097/193412303-eb29996b-2f11-4fd0-9665-9790c67183cf.png)

## My desktop
```
OS: KDE Neon User edition - 5.25
DE: KDE Plasma 5.25.5
```
I hope for a response!

**Comment by qewer33** [comment]
Should be fixed now. Can you try it and see if you still experience the issues before I upload it to the KDE Store?

Clone the repo and run `./install.rb`. Or you can copy the colorscheme files in `colorschemes` to `.local/share/color-schemes`.

**Comment by stepanzubkov** [comment]
I tried it and it works properly. Thank you for response!
